adminUser:
  password: vault:whipbitter/adminUser:password
  username: admin
dashboardAuthID: vault:whipbitter:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:whipbitter:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:whipbitter/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:whipbitter/prow:hmacToken
